POST http://localhost:8081/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0MDA3IiwidXNlcklkIjo5LCJyb2xlIjoiVVNFUiIsImlhdCI6MTc4ODI0NTYwNywiZXhwIjoxNzg4MzMyMDA3fQ.YEumbbGpM_FT0J-wpOMa33NpDWtHwio9t3cVpZOWBZs
Content-Type: application/json

{
  "productId": 7
}